### ISSUE TITLE
Do not parse buffers as strings.

### ISSUE THREAD

**Issue by aruiz** [TimMisiak/dbgrs#1]
https://github.com/TimMisiak/dbgrs/blob/43c0c3e8c7237c681b301e5e0827e27e95b508e3/src/main.rs#L11

Parsing the cmdline as if it was a buffer C style is a bad idea and it leads to the kind of bugs C leads to.

Import it as an OsString or &OsStr first and find a sensible way to parse from there safely.

**Comment by aruiz** [comment]
Actually you may want to try ```std::env::args()``` to get the arguments rather than the raw Windows API call, it should give you sanitized and safe strings to manipulate.

**Comment by TimMisiak** [comment]
Accidentally linked the wrong issue... reopened this.
